name: Refresh Raw Cache

on:
  push:
    branches:
      - main  # 你的默认分支是 main

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Purge CDN Cache
        run: |
          curl -X PURGE "https://raw.githubusercontent.com/carsgz/myclash/main/Add2GlobalSites03.list"
          curl -X PURGE "https://raw.githubusercontent.com/carsgz/myclash/main/Clash-mini99.ini"
          curl -X PURGE "https://raw.githubusercontent.com/carsgz/myclash/main/Clash-mini10.ini"
          curl -X PURGE "https://raw.githubusercontent.com/carsgz/myclash/main/Clash-mini11.ini"
          curl -X PURGE "https://raw.githubusercontent.com/carsgz/myclash/main/Direct_add01.list"
          curl -X PURGE "https://raw.githubusercontent.com/carsgz/myclash/main/Add2buyee.list"
          curl -X PURGE "https://raw.githubusercontent.com/carsgz/myclash/main/ChinaDNS.list"
